### ISSUE TITLE
Custom BEE2 Build: Misinformation

### ISSUE THREAD

**Issue by electrovoyage** [benjaminpants/bsoa#7]
Hello, i am @TPEcool and i have a message:
`You do NOT have to use the custom BEE2 build! Just unpack the folder where there is a file saying not to unpack it and make that folder's contents into either a .zip or a .beepack and it will work JUST FINE! Tested on my own experience on BEE2.4.41.0!`
Hope you understand.

**Comment by electrovoyage** [comment]
I mean, discovered on my experience.

**Comment by benjaminpants** [comment]
updated the install instructions, thanks

**Comment by electrovoyage** [comment]
> updated the install instructions, thanks

You're welcome!
